env: env
database:
  host: 127.0.0.1
  port: 3307
  user: root
  password: qBs!c27Mqw
  name: test



authRedis:
  password: Hexian%!g5tg
  db: 11
  host: 127.0.0.1 #172.18.214.173:6379
  port: 6379


logDir: /Users/xixianbin/logs