env: dev
database:
  host: 172.18.121.176
  port: 3306
  user: root
  password: qBs!c27Mqw
  name: test



authRedis:
  password: Hexian%!g5tg
  db: 11
  host: 172.18.214.173 #172.18.214.173:6379
  port: 6379


logDir: /Users/xixianbin/logs